version: '3.1'
services:
  db:
    image: mariadb:10.3
    restart: always
    environment:
      MYSQL_DATABASE: 'smeup'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3307:3306'
    volumes:
      - ./tmp/mysql:/var/lib/mysql


